### ISSUE TITLE
Migraciones de incubadoras

### ISSUE THREAD

**Issue by SSegundoGonzales** [SSegundoGonzales/Institutos_incubadoras#4]
crear migraciones de las tablas que integren el proceso de monitoreo de proyectos de emprendimiento, tomar en cuenta  https://www.youtube.com/watch?v=A-tfCsCwe00&ab_channel=WEBTD para describir a que se refiere algunos campos que sean confusos.

**Comment by BBenitoS** [comment]
por cocncluir
